# Generated by Django 2.2 on 2019-06-09 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendernewspaper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('contact', models.IntegerField()),
                ('otp', models.IntegerField()),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Deactive')], default=2)),
            ],
        ),
        migrations.CreateModel(
            name='NewspaperDesgineBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField(null=True)),
                ('width', models.IntegerField(null=True)),
                ('date', models.DateField(null=True)),
                ('image', models.CharField(max_length=200)),
                ('price', models.IntegerField(null=True)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (2, 'Deactive')], default=2)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vendernewspaper.City')),
                ('newspaper_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vendernewspaper.NewspaperName')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usernewspaper.User')),
            ],
        ),
    ]
