# Generated by Django 2.2.2 on 2019-06-21 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usernewspaper', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewspaperDesgineBooking',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
